import { useEffect, useState } from "react";
import API from "../../services/api";
import { syncOfflineTransactions } from "../../services/syncService";

const statusColors = {
  COMPLETED: "text-green-400",
  PENDING: "text-yellow-400",
  PENDING_SYNC: "text-orange-400",
  PENDING_SENT: "text-orange-400",
  SCANNED: "text-blue-400",
  EXPIRED: "text-red-400",
  FAILED: "text-red-500",
};

const Transactions = () => {
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [userId, setUserId] = useState(null);
  const [pendingCount, setPendingCount] = useState(0);

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user") || "{}");
    setUserId(user?.id);
    fetchTransactions();
    checkPendingOffline();
  }, []);

  const checkPendingOffline = () => {
    const queueStr = localStorage.getItem("offlinePendingTransactions");
    if (queueStr) {
      setPendingCount(JSON.parse(queueStr).length);
    } else {
      setPendingCount(0);
    }
  };

  const handleSync = async () => {
    setSyncing(true);
    const result = await syncOfflineTransactions();
    alert(result.message);
    setSyncing(false);
    checkPendingOffline();
    fetchTransactions();
  };

  const fetchTransactions = async () => {
    try {
      setLoading(true);
      const res = await API.get("/transactions");
      let apiTx = res.data.transactions || [];

      // Merge local pending transactions instantly
      let allLocalTxs = [];

      // 1. Pending Received (Scanned by us)
      const queueStr = localStorage.getItem("offlinePendingTransactions");
      if (queueStr) {
        const queue = JSON.parse(queueStr);
        const pendingTxs = queue.map(q => ({
          _id: "local_" + q.transactionId,
          transactionId: q.transactionId,
          voucherId: q.voucherId,
          amount: q.amount,
          status: "PENDING_SYNC",
          createdAt: q.timestamp || Date.now(),
          sender: "local", // It's received by us
        }));
        allLocalTxs = [...allLocalTxs, ...pendingTxs];
      }

      // 2. Pending Sent (Generated by us)
      const sentStr = localStorage.getItem("offlineSentTransactions");
      if (sentStr) {
        const sentQueue = JSON.parse(sentStr);
        // Filter out any that have already been synced (exist in apiTx) or have expired (older than 60s)
        const unsyncedSent = sentQueue.filter(q => {
          const isSynced = apiTx.some(t => t.transactionId === q.transactionId);
          const isExpired = (Date.now() - (q.timestamp || Date.now())) > 60000; // 60 seconds
          return !isSynced && !isExpired;
        });
        
        const sentTxs = unsyncedSent.map(q => ({
          _id: "local_sent_" + q.transactionId,
          transactionId: q.transactionId,
          voucherId: q.voucherId,
          amount: q.amount,
          status: "PENDING_SENT",
          createdAt: q.timestamp || Date.now(),
          sender: userId, // Sent by us
        }));
        
        allLocalTxs = [...allLocalTxs, ...sentTxs];
        
        // Cleanup synced/expired ones from localStorage
        if (unsyncedSent.length !== sentQueue.length) {
            localStorage.setItem("offlineSentTransactions", JSON.stringify(unsyncedSent));
        }
      }

      if (allLocalTxs.length > 0) {
        // Sort local txs by date descending
        allLocalTxs.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
        setTransactions([...allLocalTxs, ...apiTx]);
      } else {
        setTransactions(apiTx);
      }

    } catch (err) {
      console.log(err);
      
      // If offline and API fails, show at least the pending ones
      const queueStr = localStorage.getItem("offlinePendingTransactions");
      if (queueStr) {
        const queue = JSON.parse(queueStr);
        const pendingTxs = queue.map(q => ({
          _id: "local_" + q.transactionId,
          transactionId: q.transactionId,
          voucherId: q.voucherId,
          amount: q.amount,
          status: "PENDING_SYNC",
          createdAt: q.timestamp || Date.now(),
          sender: "local",
        }));
        setTransactions(pendingTxs);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen text-white">

      <div className="flex items-center justify-between mb-8">
        <h1 className="text-4xl font-bold">Transaction History</h1>
        <div className="flex gap-4">
          {pendingCount > 0 && (
            <button
              onClick={handleSync}
              disabled={syncing}
              className="bg-green-600 hover:bg-green-700 transition px-5 py-2 rounded-xl text-sm font-semibold flex items-center gap-2"
            >
              {syncing ? "Syncing..." : `Sync Offline (${pendingCount})`}
            </button>
          )}
          <button
            onClick={fetchTransactions}
            className="bg-gray-700 hover:bg-gray-600 transition px-5 py-2 rounded-xl text-sm font-semibold"
          >
            🔄 Refresh
          </button>
        </div>
      </div>

      {loading ? (
        <div className="text-center text-gray-400 mt-20 text-lg">
          Loading transactions...
        </div>
      ) : transactions.length === 0 ? (
        <div className="text-center text-gray-400 mt-20">
          <p className="text-5xl mb-4">📭</p>
          <p className="text-xl">No transactions yet</p>
          <p className="text-sm mt-2">Make a payment to see it here</p>
        </div>
      ) : (
        <div className="space-y-4">
          {transactions.map((tx) => {
            const isSender = tx.sender === userId || tx.sender?._id === userId;
            const isCompleted = tx.status === "COMPLETED";

            return (
              <div
                key={tx._id}
                className="bg-[#161B33] rounded-2xl p-6 border border-gray-700/50 hover:border-violet-500/40 transition"
              >
                <div className="flex items-center justify-between">

                  {/* Left: direction + amount */}
                  <div className="flex items-center gap-4">
                    <div className={`text-3xl w-12 h-12 flex items-center justify-center rounded-full ${
                      isSender ? "bg-red-500/10" : "bg-green-500/10"
                    }`}>
                      {isSender ? "📤" : "📥"}
                    </div>
                    <div>
                      <p className="font-semibold text-lg">
                        {isSender ? "Payment Sent" : "Payment Received"}
                      </p>
                      <p className="text-gray-400 text-sm mt-1">
                        Voucher: {tx.voucherId?.slice(0, 12)}...
                      </p>
                      <p className="text-gray-500 text-xs mt-1">
                        {new Date(tx.createdAt).toLocaleString()}
                      </p>
                    </div>
                  </div>

                  {/* Right: amount + status */}
                  <div className="text-right">
                    <p className={`text-2xl font-bold ${
                      isSender ? "text-red-400" : "text-green-400"
                    }`}>
                      {isSender ? "-" : "+"}₹{tx.amount}
                    </p>
                    <span className={`text-sm font-semibold mt-1 block ${statusColors[tx.status] || "text-gray-400"}`}>
                      ● {tx.status}
                    </span>
                  </div>

                </div>

                {/* Transaction ID */}
                <div className="mt-4 pt-4 border-t border-gray-700/50 flex justify-between text-xs text-gray-500">
                  <span>ID: {tx.transactionId?.slice(0, 20)}...</span>
                  {tx.completedAt && (
                    <span>Completed: {new Date(tx.completedAt).toLocaleTimeString()}</span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

    </div>
  );
};

export default Transactions;